print("Hi, it`s my first home work")
print("use git branch --set-upstream-to=origin/<branch> master")
print("Этот файл будет являться основой для работы с GitHub и во втором домашнем задании")
print("second change for home work 2")
print("third change for home work 2")
